version: '2.1'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      XDEBUG_CONFIG: mode=debug client_host=host.docker.internal client_port=9003 start_with_request=yes xdebug.log=/tmp/xdebug.log 
    container_name: myProject
    image: dibclient:angular
    volumes:
      - ./:/dropinbase
    ports:
    - 80:80
    - 443:443

