<?php

/* EXAMPLE CODE - see /nav/dibexComponentsSelects */

class CustomDropdownList {

    public $displayErrorsInBrowser = FALSE;
	public $count = 0;

    /**
	* Returns an array of (id, display_value) pairs generated by the SQL query linked to a specific $containerItemId
	* @param int $containerItemId 
	* @param int $page
	* @param int $page_size
	* @param string $query used with SQL LIKE to filter values. If of the form p__x it is assumed that x is the primary key value of a specific record's value to return. If d__x then x is the display value.
	* @param string $activeFilter name of the filter to apply
	* @param array $filterParams associative array of possible SQL parameter values. It is normally the flattened clientData array.
	* @param string $phpFilter SQL Where clause that may contain PDO params - if present it overrides where_clause and activeFilter
	* @param array $phpFilterParams associative array of PDO parameter values for $phpFilter
	* @param string $pageNoFromValue - NOT ACTIVE
	* @param boolean $showUsedOnly return only values used in the database
	* 
	* @return array of (id, display_value) pairs
	*/
    public function getList($containerItemId, $page=1, $page_size=40, $query='', $activeFilter=null, $filterParams=null, $phpFilter='', $phpFilterParams=array(), $pageNoFromValue=null, $showUsedOnly = false) {
    	if(empty($page) || $page<=0) $page = 1;
        if(empty($page_size) || $page_size<0) $page_size = 40;
        
        $order_by = '';
        $criteria = '';
        $params = array();
        $permCrit = ''; // any permissions criteria
        $permParams = array(); // any associated parameters for permissions criteria
        
        // Set SQL parts 
        $totalSql = " SELECT Count(*) AS totalcount FROM test_client c ";
        $sql = "c.id AS id, c.name AS id_display_value ";
        $from_clause = "test_client c ";
        $display_field = "c.name";
        $pkey = "c.id";
        $order_by = (empty($phpFilter)) ? ' ORDER BY c.name' : '';

        // Process user filter
        if(!empty($query)) {
            $query = urldecode($query);

            $pkeyOrDisplayPrefix = substr($query, 0, 3);
            if($pkeyOrDisplayPrefix === 'p__' || $pkeyOrDisplayPrefix === 'd__') {
                // handle lookup of a single record for a specific primary key or display value
                // used when eg dropdown value is set programmatically or a form record loads
                $sField = ($pkeyOrDisplayPrefix === 'p__') ? $pkey : $display_field;
                $params = array(":f1" => substr($query, 3));
                
                if(in_array($params[':f1'], array('null', 'undefined')))
                    $params = array(":f1" => NULL);
                
                $criteria = " $sField = :f1";

                // If where_clause had any PDO parameters that could be for permission purposes, include the criteria 
                if($permCrit !== '') {
					$criteria .= ' AND (' . $permCrit . ')';
					$params = array_merge($params, $permParams); 
                }
            
            } else {
                // Change following to '%'.$query.'%' if needed
                $params[":f1"] = $query.'%';

                if($criteria === '')
                    $criteria = $display_field . ' LIKE :f1';
                else
                    $criteria = "($criteria) AND ($display_field LIKE :f1)";
            }
        }

        // *** NOTE: if phpFilter present it overrides where_clause and activeFilter
        if(!empty($phpFilter)) {
        	$criteria = str_replace(array('dib__Pkey', 'dib__DisplayField'), array($pkey, $display_field), $phpFilter);
        	$params = $phpFilterParams;
        }

        if($criteria) $criteria = ' WHERE ' . $criteria;
        
        // Template: MySql - Get SQL for paging purposes for database engines that support the LIMIT keyword. Used in eg Table.php.
        if($page === 1)
            $limit = ' LIMIT ' . $page_size;
        else
            $limit = ' LIMIT ' . ($page_size * ($page - 1)) .  ', ' . $page_size;
        
        $sql = " SELECT $sql FROM $from_clause $criteria $order_by $limit";

        // Get the data
        $records = Database::execute($sql, $params, DIB::DBINDEX);

        // Get $filteredCount
        if(substr($query, 0, 3) === 'p__' || substr($query, 0, 3) === 'd__')
            $filteredCount = 1;
        else {
            $filterCountRst = Database::fetch($totalSql . $criteria, $params, DIB::DBINDEX);

            if($filterCountRst === FALSE)
                return array('error', "Error! Could not read dropdown data information. Please contact the System Administrator");
            
            $filteredCount = intval($filterCountRst["totalcount"]);			
        }

        if($records === FALSE)
            return array('error', "Error! Could not read dropdown data information. Please contact the System Administrator");
        
        return array($records, $filteredCount);
    }
    
}
